name: pengajual_judul
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.5.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  file_picker: ^5.2.0+1
  firebase_core: ^1.24.0
  firebase_storage: ^10.3.10
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.1.5
  intl: ^0.17.0
  pdf: ^3.8.3
  printing: ^5.9.3
  shimmer: ^2.0.0
  stacked: ^3.0.0
  stacked_hooks: ^0.2.2
  stacked_services: ^0.9.5
  unicons: ^2.1.0
  url_launcher: ^6.1.6
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.8.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/

  fonts:
    - family: YanoneKaffeesatz
      fonts:
        - asset: assets/fonts/YanoneKaffeesatz-Regular.ttf
          weight: 400
        - asset: assets/fonts/YanoneKaffeesatz-Medium.ttf
          weight: 500
        - asset: assets/fonts/YanoneKaffeesatz-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/YanoneKaffeesatz-Bold.ttf
          weight: 700
