// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk-7f5XazWBekxujZAU1S_CqCmmdB6DXE',
    appId: '1:912448881273:android:ca222248ad20e284e78aa8',
    messagingSenderId: '912448881273',
    projectId: 'pengajuan-judul-classification',
    storageBucket: 'pengajuan-judul-classification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKmhKKoFl9tbMz8tlg3WnxrmpieqKVSvU',
    appId: '1:912448881273:ios:ef4105807a0fa15fe78aa8',
    messagingSenderId: '912448881273',
    projectId: 'pengajuan-judul-classification',
    storageBucket: 'pengajuan-judul-classification.appspot.com',
    iosClientId: '912448881273-h9ugdak2l23mi81tkjv0cvjq8jdb42lt.apps.googleusercontent.com',
    iosBundleId: 'com.example.pengajualJudul',
  );
}
